version: 0.22

phases:
  install:
    runtime-versions:
      java: openjdk17
    commands:
      - echo "Installing dependencies..."
      - apt-get update
      - apt-get install -y maven
  build:
    commands:
      - echo "Building application..."
      - mvn clean install -DskipTests=true
  post_build:
    commands:
      - echo "Packaging application for deployment..."
      - mv target/*.jar MyApp.jar
      - echo "Running the application..."
      - java -jar MyApp.jar
artifacts:
  files:
    - MyApp.jar
